## ############################################################################
## This file is generated by orcka, and can be empty by default.
## orcka sets TAG values calculated according to criteria specified in
## docker-sha.yml and service ancestry (target.depends_on) in docker-bake.hcl
## ############################################################################

AUDIT_ENGINE_TAG_VER      = "20250929_083440_8e117c7a48692bde97555ec24fbd2901217a9b38"
INVOICE_API_TAG_VER       = "20250929_083440_622ef6f69f1b29030681e3d5743d21a887bc17df"
LEDGER_PORTAL_TAG_VER     = "20250929_083440_42509e9adbb5659f389cc6e550ca3b834728d7dd"
AUDIT_ENGINE_PULL_POLICY  = "never"
INVOICE_API_PULL_POLICY   = "never"
LEDGER_PORTAL_PULL_POLICY = "never"